### PR TITLE
Add doc on partitioning

### PR DESCRIPTION
**Pull request by macintux**
An old gist of mine capturing relationships between ring size, vnodes, and partitions.

### CODE REVIEW

**Comment by gordonguthrie** [comment]
Can you add 3 sections to make it clear who should read it and why:

# Introduction - what it is

# Purpose - what it is for

# Scope - what it covers

**Comment by hmmr** [comment]
+1 bb07f5f

**Comment by macintux** [comment]
@gordonguthrie Introduction added, created some sectioning to make the doc appear to be a little less haphazard

**Comment by gordonguthrie** [comment]
+1

**Pull request merged**
