### PR TITLE
Remove extra erl_opts

### PR DESCRIPTION
**Pull request by DeadZen**
Remove duplicate erl_opts, keep debug_info

### CODE REVIEW

**Comment by seancribbs** [comment]
Should probably add fail_on_warning in there to replace warnings_as_errors.

**Comment by DeadZen** [comment]
I thought that, but decided since riak_core is meant to be included in other distributed applications; it might be dev overkill.

**Comment by seancribbs** [comment]
@DeadZen Oh, I just meant that the option name has changed, was deprecated in R14. Unless I don't remember correctly?

**Comment by DeadZen** [comment]
Gotcha, either way, I think it is best to leave it out of this rebar.config, for a few reasons:
It may prematurely impede development with riak_core and it can always be added to the embedding application.
Additionally the extra erl_opts, prevented it along with debug_info from being applied previously anyway.
I believe removing the additional erl_opts and keeping just the debug_info, is the path of least astonishment.

**Comment by rzezeski** [comment]
@seancribbs It's still `warning_as_errors`.  I'm going to accept the patch as-is.  It can always be added against later if need be.

@DeadZen  Looks good to me.  I'm merging.

**Pull request merged**
