### PR TITLE
Add `dvv_enabled=true` to default props for typed buckets

### PR DESCRIPTION
**Pull request by russelldb**
Even though this is a kv only option

### CODE REVIEW

**Comment by russelldb** [comment]
Assigned you @cmeiklejohn, since we discussed this approach yesterday.

**Comment by cmeiklejohn** [comment]
:+1: if there is no other way.

**Comment by russelldb** [comment]
@cmeiklejohn it's bors'd, please to be +1'ing a hash

**Comment by cmeiklejohn** [comment]
:+1: cf0972d

**Comment by russelldb** [comment]
@borshop merge

**Comment by jrwest** [comment]
i realized we didn't have an issue to track the awful thing that is hardcoded bucket type defaults. no longer: https://github.com/basho/riak_core/issues/569

**Pull request merged**
