### PR TITLE
Update to the new poolboy API

### PR DESCRIPTION
**Pull request by Vagabond**
Worker arguments are passed as a separate list, now.

### CODE REVIEW

**Comment by rzezeski** [comment]
Doing a fly-by pass on this PR...is this still relevant?

**Comment by Vagabond** [comment]
This is absolutely something we need to do, except it may be even more involved now, because of all the changes upstream.

**Comment by slfritchie** [comment]
@Vagabond Time for some belated repo curating ... is there any plan to fix this for Riak 2.0?

**Comment by slfritchie** [comment]
I know you're busy, Andrew, but ... re-ping?

**Comment by rzezeski** [comment]
Setting milestone to 2.1 since it's something we absolutely need to do but too late for 2.0.

**Comment by jrwest** [comment]
leaving at milestone `2.1`

**Comment by JeetKunDoug** [comment]
@seancribbs is this change still necessary? If so, what do we do about our branch of poolboy? Update ours to latest?

**Comment by Vagabond** [comment]
Run the quickcheck tests again, make sure things are still good and update, yeah.

IIRC, some of the poolboy changes caused a minor problem with the EQC tests around worker exits, but I think it was a cosmetic problem, not a property violation. Make sure you run a lot of iterations of the tests.

**Comment by JeetKunDoug** [comment]
FYI - this PR is superseded by https://github.com/basho/riak_core/pull/639.

**Pull request closed without merging**
