### PR TITLE
Add token management to Background manager.

### PR DESCRIPTION
**Pull request by buddhisthead**
This is an initial stab at adding token management to the background manager.

Token manager is broken out to a separate gen_server.
Token calls are available in the background manager and proxied to the token manager server.
Changed enabled/disabled in BG manager to affect BOTH subsystems.
Renamed enable/disable for locks to enable_lock/disable_lock to match API for tokens: enable_tokens/disable_tokens

Comments are welcomed.

### CODE REVIEW

**Comment by jrwest** [comment]
Re: proxying through bg mgr module, i wonder if it would just be better to pull bolth APIs into third module instead. Thoughts?

**Comment by buddhisthead** [comment]
Yeah, I was going to suggest that we extract the lock manager to it's own module. And proxy both. Would make bg module clean and more of a one-stop-shopping for all BG work and monitoring.

**Comment by buddhisthead** [comment]
@jrwest Actually, it occurs to me no that I didn't see your EQC tests in your branch. Did you already merge another branch with those? I might need to rebase this PR.

**Comment by jrwest** [comment]
@buddhisthead the EQC test isn't included because it needs to be rewritten to use `eqc_temporal`. What I originally had can be found here: https://gist.github.com/jrwest/c543a4e57e9edf5ce5fe#file-riak_core_bg_manager_eqc-erl

**Comment by slfritchie** [comment]
Chris: I'm in a fit of PR review & shepherding.  When your background manager work has finished review & merged, would you mind taking care of the PRs and issues associated with it (such as this and #364 and others?) and tidy them up?  Many thanks in advance.

**Comment by buddhisthead** [comment]
@slfritchie Absolutely.

**Comment by buddhisthead** [comment]
https://github.com/basho/riak_core/pull/484 replaced this one. And it has merged :-)

**Pull request closed without merging**
