### PR TITLE
Drop console support for 'all' keyword for global permissions, fix typo

### PR DESCRIPTION
**Pull request by macintux**
- `riak_core_console` supported the concept of granting/revoking all permissions, but `riak_core_security` does not implement it, resulting in ugly RPC errors. Dropped. Thanks @metadave for the discovery.
- In an affront to humanity I misspelled "Successfully" in my last PR. Fix.

/cc @Vagabond

### CODE REVIEW

**Comment by Vagabond** [comment]
Still nothing for the dialyzer issue?

**Comment by macintux** [comment]
Ready for review again. Let me know if you want me to squash all this

**Comment by Vagabond** [comment]
Yeah, a squash would be nice. Looks fine otherwise.

**Comment by macintux** [comment]
Squashed

**Comment by Vagabond** [comment]
+1

**Comment by macintux** [comment]
Merged

**Pull request merged**
