### PR TITLE
Port 1.4 changes to the 2.0 branch.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Port 1.4 changes to the 2.0 branch.

@metadave

### CODE REVIEW

**Comment by bookshelfdave** [comment]
We'll need to do something w/ the ranch dep: https://github.com/basho/riak_core/blob/develop/rebar.config#L15

**Comment by cmeiklejohn** [comment]
In what way?

**Comment by bookshelfdave** [comment]
it only exists in riak_core because of the conn_mgr stuff. It should probably go back to repl.

**Comment by cmeiklejohn** [comment]
Added commit to remove ranch dependency.

**Comment by bookshelfdave** [comment]
+1

**Pull request merged**
