### PR TITLE
Fix minor display bug with security sources

### PR DESCRIPTION
**Pull request by macintux**
Address basho/riak#470. Any security source with `all` as the only "member" would be displayed twice via `riak-admin security print-sources`.

Thanks to @lordnull for chasing this down.

### CODE REVIEW

**Comment by seancribbs** [comment]
Taking review.

**Comment by seancribbs** [comment]
Yielding review, I can't get develop to be startable thanks to some linkage error in eleveldb NIF.

**Comment by lordnull** [comment]
Manual testing works for me.

Just the all source:

```
+--------------------+------------+----------+----------+
|       users        |    cidr    |  source  | options  |
+--------------------+------------+----------+----------+
|        all         |127.0.0.1/32|  trust   |    []    |
+--------------------+------------+----------+----------+
```

After adding a user, and source:

```
+--------------------+------------+----------+----------+
|       users        |    cidr    |  source  | options  |
+--------------------+------------+----------+----------+
|         a          |127.0.0.1/32|  trust   |    []    |
|        all         |127.0.0.1/32|  trust   |    []    |
+--------------------+------------+----------+----------+
```

After removing the all source:

```
+--------------------+------------+----------+----------+
|       users        |    cidr    |  source  | options  |
+--------------------+------------+----------+----------+
|         a          |127.0.0.1/32|  trust   |    []    |
+--------------------+------------+----------+----------+
```

This gets a :+1: from me.

**Comment by lordnull** [comment]
:+1: 44147c3

**Comment by macintux** [comment]
@borshop retry

**Comment by macintux** [comment]
@borshop merge

**Pull request merged**
