### PR TITLE
Move to gen_fsm_compat

### PR DESCRIPTION
**Pull request by Licenser**
With erlang 20 gen_fsm is marked as depricated to make place for
gen_statem. While gen_statem is sure great it feels just silly to
move perfectly good gen_fsm code to gen_statem just because.

As gen_fsm will eventually go away keeping it and just turning off
warnings also isn't the best solution it will just postpone the
problem.

This is the third option, gen_fsm_compat is a 1:1 copy of R19.3
gen_fsm that will keep working without deprication warnings and
in result make a move to 20+ a lot easier.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Great idea, although perhaps better for now to express the gen_fsm_compat dependency as git rather than hex.

**Comment by Licenser** [comment]
I was about to do that but then I saw that exometer already is a hex dependency so it seems hex was already required one way or another.

**Comment by ghost** [comment]
https://github.com/basho/riak_core/commit/d253e871258f73671da20a8b57e10b6fa719de65#r28837140

**Comment by ghost** [comment]
Added comment on the change to hex dependency.

**Comment by martincox** [comment]
Fixed in develop-3.0.

**Pull request closed without merging**
