### PR TITLE
Add #riak_core_fold_req_v2 record, part 1 of 2

### PR DESCRIPTION
**Pull request by slfritchie**
Move definition of ?FOLD_REQ to v2.

Add functions to riak_core_util.erl to create v2 versions of the
record: arity 1 (upgrade #riak_core_fold_req_v1 record to the v2
record), arity 2 (args = the two record elements of the v1 record)
and arity 4 (args = the four record elements of the v2 record).

Disable request forwarding in riak_core_vnode:forward_or_vnode_command()
if the request explicitly contains not-forwardable annotation.

### CODE REVIEW

**Comment by slfritchie** [comment]
IMHO this is a patch for the pre1 release.

**Comment by buddhisthead** [comment]
Do you mind if I rebase this and the kv PR onto develop? I've already done it, and tested, but have not pushed yet.

**Comment by slfritchie** [comment]
Reopening due to https://github.com/basho/riak/issues/407

**Comment by slfritchie** [comment]
For review ... the diff is messy, so reading the new code directly might be easier.  The function has been split into three stages
1. make_fold_req(), which faces the external world, impure
2. make_fold_req2(), which queries the riak_core capability, impure
3. make_fold_req3(), pure

Then the make_newest_fold_req() skips to make_fold_req3() when it needs to.

**Comment by beerriot** [comment]
Hooray, it works. I did a little cleanup, since `_req2` was unnecessary. I haven't finished the automated test, and I know there's a question we want to ask about defaulting Forwardable to false, but I'm +1 on these changes anyway.

**Pull request merged**
