### PR TITLE
Remove unnecessary function call.

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Remove function that is no longer required.

### CODE REVIEW

**Comment by rzezeski** [comment]
Seems bit-rot got to this PR.  Mind doing a rebase?

**Comment by cmeiklejohn** [comment]
@rzezeski rebased.

**Comment by rzezeski** [comment]
- [x] verify compile
- [x] verify eunit/EQC
- [x] <del>grep all of riak, riak_control, riak_cs<del>
- [x] <del>verify with @jtuple that this isn't use in debugging or something</del>

**Comment by cmeiklejohn** [comment]
This was added by me in 7ae213fe706280d5c022c6bffaf0deb6e8fd4a76 for Riak Control but became unnecessary.

**Comment by rzezeski** [comment]
Oh nice, that saves me some time.

**Comment by cmeiklejohn** [comment]
I've verified compile and eunit as well, but I'd definitely appreciate the double check.

**Comment by rzezeski** [comment]
+1 to merge, ayo close that PR.

**Comment by cmeiklejohn** [comment]
Thanks.

**Pull request merged**
