### PR TITLE
Add new utility functions to riak_core_util

### PR DESCRIPTION
**Pull request by jvoegele**
Several new utility functions added to `riak_core_util`:
- `riak_core_util:compose/2`: Compose two functions.
- `riak_core_util:compose/1`: Compose all functions in the list.
- `riak_core_util:multi_keydelete`: Allow for deleting multiple elements
   from a list based on the provided keys. Using `multi_keydelete`
   avoids such silliness as the following:

``` erlang
List1 = lists:keydelete(...),
List2 = lists:keydelete(...),
List3 = lists:keydelete(...),
```

Note that similar `compose` functions already exist in `riak_repl_ring`, but `riak_core_util` is a more suitable home for them since `riak_core` is already a dependency in all things Riak.

### CODE REVIEW

**Comment by jadeallenx** [comment]
Looks good - just curious if `develop` is the right target for this PR.

**Comment by jvoegele** [comment]
@mrallen1 What branch would you suggest as the target?

**Comment by jadeallenx** [comment]
I have no idea! :laughing: I thought you might know.

**Comment by jvoegele** [comment]
Ha, OK. My thought was land the changes on `develop` and then back port to `2.1` and `2.0`. Not sure if that is common or accepted practice though.

**Comment by jadeallenx** [comment]
I honestly don't know. @jonmeredith as the @JeetKunDoug substitute, what's the policy for where this PR should land?

**Comment by macintux** [comment]
The strategy we're attempting is oldest to newest: 2.0 -> 2.1 -> develop

**Comment by jadeallenx** [comment]
@jvoegele So I'd say, target this PR to 2.0 and forward merge it.

**Comment by jvoegele** [comment]
Thanks all. I'll recreate the PR against `2.0`.

**Pull request closed without merging**
