### PR TITLE
"Remove legacy gossip" rebased onto current develop

### PR DESCRIPTION
**Pull request by hmmr**
The original commit by @seancribbs is 1205ea4976 (#541).

Conflicts:
     src/riak_core.erl
    src/riak_core_console.erl
    src/riak_core_gossip_legacy.erl
    src/riak_core_ring.erl
    src/riak_core_ring_handler.erl

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
We need PRs for both the 2.0 and 2.1 branches as well.

**Comment by cmeiklejohn** [comment]
Oops, disregard.  Previous comment was meant for another PR.

**Comment by macintux** [comment]
Per Jon's comment, this is 2.next, hence not relevant to 2.0/2.1.

**Comment by cmeiklejohn** [comment]
Do you mind amending this commit (2bada68) to have a better commit message?  No need to say in the commit it's been rebased, just clearly specify the changes.

I'll :+1: once commit message is cleaned up.

**Comment by hmmr** [comment]
@cmeiklejohn pity @seancribbs was himself not particularly verbose in his commit.. But I'll try to give it a description as I understand it.

**Comment by cmeiklejohn** [comment]
Just do what you can to make it a bit clearer for future you.

**Comment by cmeiklejohn** [comment]
:+1: 727fa77

**Comment by cmeiklejohn** [comment]
@borshop merge

**Pull request merged**
