### PR TITLE
Add handoff.ip to core cuttlefish schema [JIRA: RIAK-3058]

### PR DESCRIPTION
**Pull request by bearcage**
Items for discussion:
- Included a validator prohibiting loopback per issue report — seems like a sane choice to me since handoff on the loopback interface is only useful for devrels, and in that case 0.0.0.0 is fine too.
- I'm not clear on if/how validators are currently tested, so I've neglected to write a test for that as yet.

### CODE REVIEW

**Comment by andrewjstone** [comment]
@aberghage I'm against the validator prohibiting loopback. I don't want to open up a handoff port publicly if I'm just running tests on my laptop.

**Comment by bearcage** [comment]
I don't have a strong feeling there; I added it since it was requested in 634, but I can see the argument either way.

**Comment by seancribbs** [comment]
Agree with @andrewjstone, validating that it's a correct IPv4/6 address should be sufficient.

`inet_parse:address/1` is what you want.

**Comment by jrwest** [comment]
fwiw, since I left the original comment in #634, I think its more important to prevent the user from doing something silly. I understand the concern while developing but I think its better to put the burden on the riak developer to protect their machine than the user from ending up in a confusing config state.

**Comment by bearcage** [comment]
Now that we're out of the collective turkey coma, any objections to merging this?

**Comment by andrewjstone** [comment]
:+1:  73a0bbd 
sorry @aberghage for the delayed +1

**Comment by seancribbs** [comment]
Should have a :+1: from another CSE.

**Comment by pyrrho** [comment]
:+1:
I mentioned to Alex in HipChat that I was surprised that the `invalid_states_test` is new. I'm assuming it's named as such to allow it to expand into a more general test.

**Comment by bearcage** [comment]
Yep, that's the notion. The core schema test suite previously didn't include anything to exercise validators, so that adds it.

**Comment by bearcage** [comment]
@borshop merge

**Comment by bashopatricia** [comment]
create jira issue

**Comment by Basho-JIRA** [comment]
Per Brian, don't need to touch this work, 2.0 and develop-2.2 branches have most up to date code.  [~bsparrow435] Can you close this if no longer needed?  Thanks 

***[posted via JIRA by Patricia Brewer]***

**Pull request merged**
