### PR TITLE
Ranch update and link to official repositroy

### PR DESCRIPTION
**Pull request by Licenser**
Riak Core links to a rather outdated version of rance that is kept in a basho repository.

For once ranch is a very well behaved library when it comes to tagging versions so it is quite possible to link to the extend repository seems like the 'cleaner' version then forking it.

There are quite some changes ( https://github.com/extend/ranch/compare/basho:0.4.0-p1...0.8.4 ) and having a one your old version is quite hard on applications using riak_core and ranch since all will blow up around it the old ranch version.

I've tried running the tests and it reports all of them OK, I could not run dialyzer since make dialyzer does not work out of the box (something about protobufs not compiled with debug info.

Cheers,
Heinz

### CODE REVIEW

**Comment by slfritchie** [comment]
Time for some belated repo curating ... @jaredmorrow Do you have any opinion about this?  @metadave Hrm, 'git blame' says that you were the last person to make edits on the lines that call the `ranch` module (riak_core_service_manager.erl).

**Comment by bookshelfdave** [comment]
Hello @Licenser -

  Ranch is used internally in Riak Enterprise and at this point, we are tied to 0.4.0-p1. We plan to upgrade this dependency, but that won't happen until after Riak 2.0 is released. 

Cheers -
Dave

**Comment by slfritchie** [comment]
New milestone: 2.1

**Comment by bookshelfdave** [comment]
ranch has been removed as a riak_core dep as of: https://github.com/basho/riak_core/pull/480

**Comment by jrwest** [comment]
Leaving on milestone `2.1`

**Comment by JeetKunDoug** [comment]
Not having reviewed the whole PR, but wondering why we still have an "Update Ranch Version" PR if Ranch isn't in riak_core any more. Can we close this, or is it still needed for something else?

**Comment by jonmeredith** [comment]
It's definitely used by repl, and probably riak_api.

On Fri, Oct 17, 2014 at 11:42 AM, Doug Rohrer notifications@github.com
wrote:

> Not having reviewed the whole PR, but wondering why we still have an
> "Update Ranch Version" PR if Ranch isn't in riak_core any more. Can we
> close this, or is it still needed for something else?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/riak_core/pull/344#issuecomment-59548793.

## 

Jon Meredith
Chief Architect
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by JeetKunDoug** [comment]
True, but it's not used in riak_core, which makes me believe this PR could be closed on riak_core, right?

**Comment by Licenser** [comment]
## I’m fine with closing it just haven’t looked at in the the last year :)

Cheers,
Heinz Nikolaus Gies
heinz@licenser.net

**Pull request closed without merging**
