### PR TITLE
Fix brops intermittent test failures

### PR DESCRIPTION
**Pull request by russelldb**
All around Pid start/registration/stop behaviour in `bprops_eqc` test. The deps stuff will need updating again when PRs merged that take us off tags and back onto branches for this dev cycle

### CODE REVIEW

**Comment by martincox** [comment]
+1.

**Comment by nickkeers** [comment]
+1 as well, fixes the problem tests

**Comment by russelldb** [comment]
Squashed merge? Or keep the messy history?

**Comment by ghost** [comment]
+1 to squash

**Pull request merged**
