### PR TITLE
disable bg manager globally

### PR DESCRIPTION
**Pull request by jrwest**
cc/ @kellymclaughlin @cmeiklejohn 

https://github.com/basho/riak_core/issues/597

### CODE REVIEW

**Comment by reiddraper** [comment]
Added 2.0-RC miletone

**Comment by reiddraper** [comment]
This looks sane, will +1 after some of the broken tests (sadness) are fixed.

**Comment by cmeiklejohn** [comment]
Can we merge this given the known failure documented in #590? cc: @reiddraper

**Comment by reiddraper** [comment]
Yes, +1 to manually merge

**Pull request merged**
