### PR TITLE
add cuttlefish mapping for vnode_management_timer

### PR DESCRIPTION
**Pull request by jrwest**

### CODE REVIEW

**Comment by jrwest** [comment]
cc/ @seancribbs

**Comment by seancribbs** [comment]
- [x] Eng +1
- [x] CSE +1

**Comment by seancribbs** [comment]
Withdrawing my +1 until there's a schema test.

**Comment by joedevivo** [comment]
YEAH!

**Comment by jrwest** [comment]
schema test pushed

**Comment by seancribbs** [comment]
Thanks @jrwest

**Comment by jrwest** [comment]
@seancribbs who should be pinged re: CSE +1?

**Comment by seancribbs** [comment]
@angrycub Is my go-to guy for that.

**Comment by angrycub** [comment]
CSE +1

**Comment by jrwest** [comment]
@seancribbs do we need the PM +1? Otherwise, can I get a @borshop +1?

**Comment by seancribbs** [comment]
:+1: 9f55d39

Spoke with @michellep, she is ok with CSE-only approval for future PRs.

**Comment by seancribbs** [comment]
The original intent of that process was to make sure we had different perspectives involved in review, and so that things like naming and documentation weren't reliant only on Engineering scrutiny (which can be biased toward technical bits rather than user concerns).

**Comment by jrwest** [comment]
@borshop merge

**Pull request merged**
