### PR TITLE
global:safe_whereis_name/1 has been removed

### PR DESCRIPTION
**Pull request by lemenkov**
There is no such function global:safe_whereis_name/1 in R15B anymore. RabbitMQ folks already replaced it with a plain global:whereis_name/1 function  - see rabbitmq/rabbitmq-server@0d3001e0e167ea2463e4c0a7ca45c3b0cb230c1f.

### CODE REVIEW

**Comment by lemenkov** [comment]
See also related issue #159.

**Comment by rzezeski** [comment]
This is related to #159

I think Riak Core should use one of the gen_server2 repos.

**Comment by rzezeski** [comment]
Heh, just realized you already referenced the other issue.  My eyes failed me.  Once the other branch lands on master I'll review this one.

**Comment by rzezeski** [comment]
@lemenkov Thank you for the contribution.

**Pull request merged**
