### PR TITLE
Add `node_confirms` default bucket props

### PR DESCRIPTION
**Pull request by russelldb**
This is an upstream PR of two PRs already merged/tested on the nhs-fork.
The original PRs are:
- https://github.com/nhs-riak/riak_core/pull/1
- https://github.com/nhs-riak/riak_core/pull/8

See https://github.com/basho/riak_kv/pull/1663 for full details. This PR supports that KV feature.

### CODE REVIEW

**Comment by ghost** [comment]
I'm getting quickcheck errors on this branch - output attached 

[out.riak_core.rdb-upstream-pr-node-confirms.txt](https://github.com/basho/riak_core/files/1771861/out.riak_core.rdb-upstream-pr-node-confirms.txt)

**Comment by russelldb** [comment]
But those errors are fixed on develop-2.2, right?

**Comment by russelldb** [comment]
Are you asking that I rebase on basho/develop-2.2 and re-push? Or fix the issue again? I kind of assumed you'd merge to develop-2.2 locally and run the tests (since that is what the end result would be after the merge.)

**Comment by ghost** [comment]
Ah - let me try the rebase/merge and see if I can get it to work - yep the errors were familiar.

**Comment by ghost** [comment]
Rebase and pass 👍 

[out.riak_core.rdb-upstream-pr-node-confirms-after-rebase.txt](https://github.com/basho/riak_core/files/1772063/out.riak_core.rdb-upstream-pr-node-confirms-after-rebase.txt)

For the record - rebar.config needed merging - after the rebase the rebar.config looked like the following (forgive the formatting) : 

```
{erl_first_files, ["src/gen_nb_server.erl", "src/riak_core_gen_server.erl",
		   "src/riak_core_stat_xform"]}.
{cover_enabled, true}.
{erl_opts, [warnings_as_errors, {parse_transform, lager_transform},
            debug_info, {platform_define, "^[0-9]+", namespaced_types},
            {platform_define, "^R15", "old_hash"}]}.
{edoc_opts, [{preprocess, true}]}.
{eunit_opts, [verbose]}.
{xref_checks, []}.
{xref_queries, [{"(XC - UC) || (XU - X - B - \"(cluster_info|dtrace)\" : Mod)", []}]}.

{deps, [
  {basho_stats   , ".*" , {git , "git://github.com/basho/basho_stats.git"      , {branch , "master"}}}        ,
  {clique        , ".*" , {git , "https://github.com/basho/clique.git"         , {branch , "develop-2.2"}}}   ,
  {eleveldb      , ".*" , {git , "git://github.com/basho/eleveldb.git"         , {branch , "2.0"}}}           ,
  {exometer_core , ".*" , {git , "git://github.com/basho/exometer_core.git"    , {branch , "master"}}}        ,
  {lager         , ".*" , {git , "git://github.com/basho/lager.git"            , {tag    , "3.2.4"}}}         ,
  {pbkdf2        , ".*" , {git , "git://github.com/basho/erlang-pbkdf2.git"    , {branch , "master"}}}        ,
  {poolboy       , ".*" , {git , "git://github.com/basho/poolboy.git"          , {branch , "develop-2.2.5"}}} ,
  {riak_ensemble , ".*" , {git , "https://github.com/basho/riak_ensemble"      , {branch , "develop-2.2"}}}   ,
  {riak_sysmon   , ".*" , {git , "https://github.com/basho/riak_sysmon.git"    , {tag    , "2.1.5"}}}         
]}.

```

**Review by ghost — APPROVED** [review]
lgtm (see comments)

**Comment by russelldb** [comment]
cheers @bryanhuntesl, I'll sort out the rebar.config. Forks and rebar.config are hard.

**Pull request merged**
