### PR TITLE
Update otp_release list in .travis.yml

### PR DESCRIPTION
**Pull request by mbbx6spp**
Changes:
- Removed R14\* Erlang version targets from `.travis.yml`
- Added R15B\* and R16B Erlang version targets to `.travis.yml`

Background:
Until this change Travis CI was building against Erlang R14 which is not
supported for Riak (KV) according to [Basho documentation](http://docs.basho.com/riak/latest/ops/building/installing/erlang/),
which states, _"Riak requires Erlang R15B01"_. The R14 builds consistently 
failed since the ring resizing change was merged.

Since `.travis.yml` was updated last (a year ago) R15B0{2-3} and R16B
were released. R16B01 and R16B02 do not appear to be offered as choices
in Travis CI yet ([according to Travis CI's documentation](http://about.travis-ci.org/docs/user/languages/erlang/)).

### CODE REVIEW

**Comment by slfritchie** [comment]
+1, thanks, and many apologies for the delay!

**Comment by jrwest** [comment]
I didn't realize we were actually relying on travis for builds anymore. They rarely seem to reflect the correct results (or well, yea its probably failing but its the wrong failure). Is there are reason we just don't remove the .yml file?

**Comment by seancribbs** [comment]
@jrwest We have already disabled the hook, they do not currently run.

**Comment by jrwest** [comment]
any reason to keep the file then? would be happy to open a quick PR to remove it (although i guess we should do the other repos too then?).

**Pull request merged**
