### PR TITLE
Don't double-format sysmon messages, unexport unused functions

### PR DESCRIPTION
**Pull request by Vagabond**
This should more safely bound the memory used when printing lots of sysmon messages, as all the formatting is done via lager's trunc_io.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Pushed rebased version of this branch [here](https://github.com/basho/riak_core/tree/adt-sysmon-format-rebased).

**Comment by kellymclaughlin** [comment]
+1 to merge. The rebased branch should merge cleanly, but careful if you merge this one there will be some conflicts.

**Comment by Vagabond** [comment]
Where do we need to merge this to for 1.3?

**Comment by kellymclaughlin** [comment]
It only _needs_ to be on master I think, but I don't see any harm in merging it to 1.2 as well.

**Comment by Vagabond** [comment]
@jaredmorrow Suggestions?

**Comment by jaredmorrow** [comment]
If it is dataloss I'd put to 1.2 also, otherwise just master.

**Comment by Vagabond** [comment]
Merged by hand to master.

**Pull request closed without merging**
