### PR TITLE
Update riak_core to use clique 0.3.0

### PR DESCRIPTION
**Pull request by nickelization**
Clique 0.3.0 introduces an extra argument that's passed to the command callbacks. The existing code in riak_core that uses clique doesn't need this extra argument, so we can just ignore it, but we still need to add an extra _ argument at the beginning of each command callback.

### CODE REVIEW

**Comment by paegun** [comment]
+1 looks great, moved up to clique 0.3.0. Thank you for clarifying the unused first arg is _BaseCmd.

**Comment by paegun** [comment]
+1 even better with the unused arg named :+1:

**Comment by paegun** [comment]
+1 ddf4c9c8a1bd6f921ebef2766ae6fae83414fa0f

**Comment by nickelization** [comment]
@borshop merge

**Pull request merged**
