### PR TITLE
timeout in riak_core_tcp_mon nodeupdown_test_

### PR DESCRIPTION
**Pull request by reiddraper**
```
module 'riak_core_tcp_mon'
  riak_core_tcp_mon: nodeupdown_test_...*timed out*
undefined
```

### CODE REVIEW

**Comment by reiddraper** [comment]
I'll at least make a PR to change this test to use a spawn.

**Comment by reiddraper** [comment]
I've added a commit to this issue. Since the failure is non-deterministic, we'll re-open this issue if this starts to come back again. cc @jrwest

**Comment by jrwest** [comment]
tests pass on buildbot but locally `make test` hung after all 370 tests passed. On `develop` that didn't happen. running again while i get some food.

**Comment by jrwest** [comment]
+1 7546c54 

next run went fine.

**Comment by reiddraper** [comment]
@borshop merge

**Pull request merged**
