### PR TITLE
Add transfer_limit config callback to handoff_cli

### PR DESCRIPTION
**Pull request by andrewjstone**
This ensures that when the limit is reduced processes exceeding the
limit get shut down. Uses already existing functionality in
riak_core_handoff_manager for the shutdown.

### CODE REVIEW

**Comment by andrewjstone** [comment]
cc @macintux

**Comment by macintux** [comment]
Force pushed a rebase onto an also-rebased `integration/riak-admin-handoff-team` branch

**Comment by macintux** [comment]
The 'help enable' output to be underspecified compared to 'enable help'. Specifically, the `[args]` are unknown until you try something, which seems risky; as a sysadmin, I'd really rather not try a command to see what happens.

```
Thunder:bin John$ ./riak-admin handoff help enable
Usage: riak-admin handoff <subcommand> [args]

Currently implemented handoff commands are:
  enable   Enable handoffs for the specified node(s)
  disable  Disable handoffs for the specified node(s)

Thunder:bin John$ ./riak-admin handoff enable help
Usage: riak-admin handoff <enable | disable> <inbound | outbound | both> [[--node | -n] <Node>] [--all]

  Enable or disable handoffs on the specified node(s).
  If handoffs are disabled in a direction, any currently
  running handoffs in that direction will be terminated.

Options
  -n <Node>, --node <Node>
      Modify the setting on the specified node (default: local node only)
  -a, --all
      Modify the setting on every node in the cluster
```

(This is outside the scope of the current PR)

Update: actually, I don't think it is. Notice that also the "enable inbound" syntax is not illustrated via "help enable".

**Comment by macintux** [comment]
Would really like to see more context-sensitive output. What exactly did I do?

```
Thunder:bin John$ ./riak-admin handoff disable inbound
Handoff setting successfully updated
Thunder:bin John$ ./riak-admin handoff enable inbound
Handoff setting successfully updated
```

E.g., is that for this node? Cluster-wide? Did I just enable or disable?

**Comment by macintux** [comment]
```
$ ./riak-admin handoff disable outbound
Handoff setting successfully updated
```

Yet, joining another node to this one works and all transfers occur. Hrm.

**Comment by macintux** [comment]
Ok, now, focusing on THIS particular PR, not a big fan of this behavior:

```
Thunder:dev1 John$ ./bin/riak-admin transfer_limit dev3@127.0.0.1
Invalid limit: dev3@127.0.0.1
Thunder:dev1 John$ ./bin/riak-admin transfer_limit help
Invalid limit: help
```

**Comment by andrewjstone** [comment]
@macintux weird. There should have to be a `set`, `show`, or `describe` in there for that to work at all. I just reproduced locally as well. Will fix.

**Comment by andrewjstone** [comment]
@macintux I just confirmed that this behavior is a result of transfer_limit being a valid 'legacy' command.  We can't change it without breaking backwards compatibility. 
https://github.com/basho/riak_ee/blob/develop/rel/files/riak-admin#L831

**Pull request merged**
