### PR TITLE
Cuttlefish RHS Substitutions

### PR DESCRIPTION
**Pull request by joedevivo**
This is the first "in the wild" use of Cuttlefish's new Right Hand Side Substitutions.

Check out the change to `ring.state_dir` for an idea of how it's changed, but basically, instead of using `{{platform_data_dir}}` at build time to determine the default, you can now reference `#(platform_data_dir)` which will be evaluated at runtime.
- [x] CSE love
- [x] ProdMgmt love
- [x] Eng love

### CODE REVIEW

**Comment by angrycub** [comment]
CSE +1

**Comment by gburd** [comment]
Why did "ring" move into the data dir?

**Comment by joedevivo** [comment]
For who knows how long `{{ring_state_dir}}` was `{{platform_data_dir}}/ring` this just moves that abstraction into cuttlefish

**Comment by angrycub** [comment]
Isn't that only on a devrel?  On a rel or package, the data dir is like /var/lib/riak, eh?

**Comment by joedevivo** [comment]
It's the same for both devrel and rel. I'm not sure about the package.

**Comment by gburd** [comment]
Honestly, I forget where it traditionally lived.

**Comment by gburd** [comment]
PM +1

**Comment by seancribbs** [comment]
Eng +1

**Pull request merged**
