### PR TITLE
Don't crash the cache when a stat mod crashes

### PR DESCRIPTION
**Pull request by russelldb**
Since calls to calculate stats are spawn_linked to ensure
that the calculating processes exits if the cache exits, the cache
will crash if a spawned process exits. This is bad. This change
traps_exits on spawned processes and enforms awaiting callers of
the error, without crashing the cache or effecting other registered
mods.

### CODE REVIEW

**Comment by rzezeski** [comment]
> This change traps_exits on spawned processes

From my limited understand it is the cache that is trapping exits, not the spawned processes.

Are there other processes that link to the cache?  It looks like if the cache gets an exit signal from a process it doesn't recognize it stops.  Is this what we want?

**Comment by rzezeski** [comment]
Are the following errors something that would be caused the the issue described here?

```
2012-07-16 23:51:53 =ERROR REPORT====
Error in process <0.5908.0> on node 'riak@10.7.7.21' with exit value: {badarg,[{riak_core_stat,'-vnodeq_stats/0-lc$^0/1-0-',1,[{file,"src/riak_core_stat.erl"},{line,159}]},{riak_core_stat,'-vnodeq_stats/0-lc$^0/1-0-',1,[{file,"src/riak_core_stat.erl"},{line,160}]},{riak_core_stat,vnodeq_stats...

2012-07-16 23:51:53 =SUPERVISOR REPORT====     Supervisor: {local,riak_core_sup}     Context:    child_terminated     Reason:     {badarg,[{riak_core_stat,'-vnodeq_stats/0-lc$^0/1-0-',1,[{file,"src/riak_core_stat.erl"},{line,159}]},{riak_core_stat,'-vnodeq_stats/0-lc$^0/1-0-',1,[{file,"src/riak_core_stat.erl"},{line,160}]},{riak_core_stat,vnodeq_stats,0,[{file,"src/riak_core_stat.erl"},{line,159}]},{riak_core_stat,produce_stats,0,[{file,"src/riak_core_stat.erl"},{line,132}]},{timer,tc,3,[{file,"timer.erl"},{line,194}]},{folsom_metrics,histogram_timed_update,4,[{file,"src/folsom_metrics.erl"},{line,163}]},{riak_core_stat_cache,'-do_get_stats/2-fun-0-',4,[{file,"src/riak_core_stat_cache.erl"},{line,163}]}]}
     Offender:   [{pid,<0.214.0>},{name,riak_core_stat_cache},{mfargs,{riak_core_stat_cache,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
2012-07-16 23:51:53 =ERROR REPORT====
webmachine error: path="/stats"
{error,{exit,{{badarg,[{riak_core_stat,'-vnodeq_stats/0-lc$^0/1-0-',1,[{file,"src/riak_core_stat.erl"},{line,159}]},{riak_core_stat,'-vnodeq_stats/0-lc$^0/1-0-',1,[{file,"src/riak_core_stat.erl"},{line,160}]},{riak_core_stat,vnodeq_stats,0,[{file,"src/riak_core_stat.erl"},{line,159}]},{riak_core_stat,produce_stats,0,[{file,"src/riak_core_stat.erl"},{line,132}]},{timer,tc,3,[{file,"timer.erl"},{line,194}]},{folsom_metrics,histogram_timed_update,4,[{file,"src/folsom_metrics.erl"},{line,163}]},{riak_core_stat_cache,'-do_get_stats/2-fun-0-',4,[{file,"src/riak_core_stat_cache.erl"},{line,163}]}]},{gen_server,call,[riak_core_stat_cache,{get_stats,riak_core},infinity]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,188}]},{riak_core_stat,get_stats,0,[{file,"src/riak_core_stat.erl"},{line,51}]},{riak_kv_wm_stats,get_stats,0,[{file,"src/riak_kv_wm_stats.erl"},{line,95}]},{riak_kv_wm_stats,produce_body,2,[{file,"src/riak_kv_wm_stats.erl"},{line,83}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,169}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,128}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,532}]}]}}
2012-07-16 23:51:54 =SUPERVISOR REPORT====
     Supervisor: {local,riak_jmx_sup}
     Context:    child_terminated
     Reason:     normal
     Offender:   [{pid,<0.1807.0>},{name,riak_jmx_monitor},{mfargs,{riak_jmx_monitor,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2012-07-16 23:51:54 =ERROR REPORT====
webmachine error: path="/stats"
{error,{error,function_clause,[{proplists,delete,[disk,{error,{not_registered,riak_kv}}],[{file,"proplists.erl"},{line,362}]},{riak_kv_wm_stats,get_stats,0,[{file,"src/riak_kv_wm_stats.erl"},{line,94}]},{riak_kv_wm_stats,produce_body,2,[{file,"src/riak_kv_wm_stats.erl"},{line,83}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,169}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,128}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,532}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,33}]}]}}
2012-07-16 23:51:54 =SUPERVISOR REPORT====
     Supervisor: {local,riak_jmx_sup}
     Context:    child_terminated
     Reason:     normal
     Offender:   [{pid,<0.5916.0>},{name,riak_jmx_monitor},{mfargs,{riak_jmx_monitor,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
```

**Comment by russelldb** [comment]
> From my limited understand it is the cache that is trapping exits, not the spawned processes.

Yeah, the cache traps, the spawned processes exit. If that is not how it reads it is what I meant to say.

**Comment by russelldb** [comment]
> Are there other processes that link to the cache? It looks like if the cache gets an exit signal from a process it doesn't recognize it stops. Is this what we want?

It is what we get always with a gen_server. Any process anywhere can link to it, crash, and bring it down. In this case I thought it best only to code for the explicit case of exits from spawned processes. Anything else seems defensive.

**Comment by russelldb** [comment]
> Are the following errors something that would be caused the the issue described here?

Yeah, so that `badarg` 

```
{badarg,[{riak_core_stat,'-vnodeq_stats/0-lc$^0/1-0-',1,[{file,"src/riak_core_stat.erl"},{line,159}]},
```

Is due to the a dead `pid` being passed to process_info. Why is it dead? I don't know. See https://github.com/basho/riak_core/blob/master/src/riak_core_stat.erl#L159

Between the call to `riak_core_vnode_manager:all_vnodes()` and the call to `process_info` the process `Pid` exits.

That is a separate issue. Any stat mod that crashes, for whatever reason, shouldn't kill the cache.

**Comment by rzezeski** [comment]
> It is what we get always with a gen_server. Any process anywhere can link to it, crash, and bring it down. In this case I thought it best only to code for the explicit case of exits from spawned processes. Anything else seems defensive.

Agreed.  I was curious if _we_ have linked anything else to the cache that could crash besides these workers?

**Comment by rzezeski** [comment]
The unit tests pass.  I'm re-running the cluster tests now that produced the failures above.

**Comment by russelldb** [comment]
>  I was curious if we have linked anything else to the cache that could crash besides these workers?

Just the supervisor, as far as I know.

>  I'm re-running the cluster tests now that produced the failures above.

Curious about this…why didn't we see these errors with old stats? Same code in riak_core_stat…curious.

**Comment by rzezeski** [comment]
Wait, now that I reread your comments are you saying my issues above are a different problem?

**Comment by russelldb** [comment]
That crash of `riak_core_stat.erl` when it works out the vnodeq length is an issue. I don't know if it is new or old. I suspect it may have been there before. The _new_ thing is that it crashes the stat cache, which breaks `/stats`. This PR stops the crash of `riak_core_stat` breaking `/stats` by isolating the stat cache from the failure. It doesn't fix that crash in riak_core_stat, which I haven't even investigated, since that code is unchanged since 1.1.*

**Comment by rzezeski** [comment]
The cluster test has now passed twice when it previously failed.  The errors I pasted above are gone.  Given they are vnode related and probably non-deterministic I'm not sure this means anything.

**Comment by russelldb** [comment]
Hmmm…I dunno, what do you want to do?

**Comment by rzezeski** [comment]
The cluster test has run 3 times successfully.  The last two times I checked the logs on all 4 nodes and none showed the previous errors.  The code looks sane to me.

+1 to merge

**Comment by rzezeski** [comment]
Just realized this is against master.  We want it against 1.2 and then merge that to master IIRC.

**Comment by russelldb** [comment]
Will re-open against 1.2 and ref this PR.

**Comment by russelldb** [comment]
Merged to 1.2, see https://github.com/basho/riak_core/pull/210

**Pull request closed without merging**
