### PR TITLE
mark AAE vnodes as internal databases for leveldb flexcache accounting

### PR DESCRIPTION
**Pull request by matthewvon**

### CODE REVIEW

**Comment by russelldb** [comment]
It _looks_ fine. And riak starts and runs with this change. However, what does it do? And how can I verify that?

**Comment by matthewvon** [comment]
To verify:
1. apply mv-flexcache branch to eleveldb,
2. apply mv-flexcache branch to leveldb,
3. start Riak
4. look at the LOG files in the aae directory, see if "is_internal_db" flag shows "true" in the options dumped at top of file.

**Comment by russelldb** [comment]
Still can't build this on any of local combo of linux | os x + erlang r15b01 - r16b02.

I know others have failed, and some claim to succeed. Somewhat stalled at this point.

**Comment by russelldb** [comment]
Ok, finally, I have managed to build, run, and verify this branch. It is a bit of a mess as far as which commits are included, but for your commits? Plus one (finally, sorry for the long hiatus.)

**Pull request merged**
