### PR TITLE
Move tcp-mon, connection and service manager supervisors from replication to core.

### PR DESCRIPTION
**Pull request by buddhisthead**
This is the matching PR for replication below. This is the final move to migrate the connection and service
managers from replication into their proper home in core. The riak_core_tcp_mon supervisor also belongs here.

If you build/test this on riak_ee, you will need the following PR as well, which is recently rebased on develop.
https://github.com/basho/riak_repl/pull/398

### CODE REVIEW

**Comment by seancribbs** [comment]
@buddhisthead Looks like you missed adding the module.

**Comment by buddhisthead** [comment]
@seancribbs You were so right! I had to re-create this module because, of course, I had blown away the local version. If you don't mind having a look, I would really appreciate it. Thanks.

**Comment by cmeiklejohn** [comment]
I've built this and ran the eunits and it looks good.  Also, I've also verified that this new change works in the Riak ETL client code, where we manually started the supervisor.  However, this branch should be squashed because it contains a bunch of intermediary commits that don't build independently and would be better as a single commit into Riak Core.

**Comment by buddhisthead** [comment]
Thanks, Chris. I will visit sifu for git squash training next.

**Comment by buddhisthead** [comment]
Ah, squash is cool. Much better, but had to force push this branch. Please update if you have a local copy.

**Comment by cmeiklejohn** [comment]
Looks great to me; waiting for a Core/KV :+1:

**Comment by buddhisthead** [comment]
@cmeiklejohn rebased on latest develop

**Comment by slfritchie** [comment]
Ping?

**Comment by seancribbs** [comment]
@slfritchie Seems like since riak_core_connection_mgr and friends moved back to repl, this won't be needed. Confirm @cmeiklejohn ?

**Comment by cmeiklejohn** [comment]
Correct; closing.

**Pull request closed without merging**
