### PR TITLE
Use a sliding one minute window not a EWMA meter

### PR DESCRIPTION
**Pull request by russelldb**
Depends on https://github.com/boundary/folsom/pull/27…

Use a one minute count and total count, not a weighted moving average.

### CODE REVIEW

**Comment by rzezeski** [comment]
I believe `rebar.config` needs to be updated to pull the Basho fork of folsom now.  No?

**Comment by russelldb** [comment]
Yes :$

**Comment by russelldb** [comment]
Well, I was hoping Joe W. would merge upstream…

**Comment by rzezeski** [comment]
I don't think we have the convenience of waiting for that to happen.

**Comment by russelldb** [comment]
updated rebar.config

**Comment by rzezeski** [comment]
+1 to merge

**Pull request merged**
