### PR TITLE
Avoid use of ets:match() in hot code paths

### PR DESCRIPTION
**Pull request by slfritchie**
Profiling with DTrace on Solaris suggests that ets:match() is causing
a much higher than necessary lock contention rate within the Erlang
R14B03 and R14B04 VMs.  Eliminating ets:match() in the riak_core and
riak_kv applications is substantial when using Pthread locking instead
of Ericsson's hand-tuned locking (which is the default).  The results
are more ambiguous when the default locking strategy is used.

### CODE REVIEW

**Comment by rzezeski** [comment]
Scott, not sure if you already know about this but a few releases ago there were concurrency options added to ETS: `read_concurrency` and `write_concurrency`.  The `read_concurrency` one showed me favorable gains on a highly concurrent (running on nodes with 16 cores), read heavy load of a public ETS table on an old project I did.  Might be worth a look for an additional boost if needed.

**Comment by rzezeski** [comment]
Before I review this it needs to be rebased against master.  A lot has changed since Nov 17th.

**Comment by slfritchie** [comment]
Ryan, the patch is destined both for master and 1.0 branches.
The code as-is is for the 1.0 branch, IIRC.  For master, I'll create
another pull request -- the diffs will be against a different module,
but otherwise the diffs will likely be unchanged.

**Comment by rzezeski** [comment]
This PR has be made obsolete by https://github.com/basho/riak_core/pull/132

**Pull request closed without merging**
