### PR TITLE
merkerl: fixes potential clobbering when turning a leaf into an inner

### PR DESCRIPTION
**Pull request by andrewoswald**
When adding several values to a tree, I occasionally noticed that some values didn't get picked up.  After looking at the clause for inserting an MI into a "leaf" (line #158), the code that inserted the leaves into an orddict via their offset_key/2 results looked suspicious.  Indeed, if those two results were identical, the orddict values would clobber.  The solution is to simply create the inner using _only_ the initial leaf and then to subsequently call the mi_insert1 function providing the newly created inner as its Tree arg.

I added a test that demonstrates what would otherwise be a clobbered value (assuming the offset is either 0 or 8).  Its keys, <<"riak.com42">> and <<"riak.com452">>, respectively "sha" to:
<<21,236,177,213,57,7,41,130,41,112,195,213,10,85,84,31,115,84,156,40>>
<<21,236,167,160,142,11,39,35,69,14,183,49,144,41,75,9,17,141,189,202>>

Interested in your thoughts.

thanks!
-andy

### CODE REVIEW

**Comment by jonmeredith** [comment]
Hi Andrew, I'm sorry this has lingered for a while - I've updated our task tracking system to make sure we look at it sooner rather than later.

**Comment by andrewoswald** [comment]
No worries Jon.  I should have also submitted a proper ticket for tracking purposes.  Thanks again!

**Comment by argv0** [comment]
Looks good and tests pass - verified fix with Justin Sheehy (original author).

**Comment by andrewoswald** [comment]
Thanks Andy.  Hope all is well!

**Pull request merged**
