### PR TITLE
Fix riak_core_util:compose functions

### PR DESCRIPTION
**Pull request by jvoegele**
Fix the `compose/1` and `compose/2` functions in `riak_core_util`:
* Compose lists of functions from right-to-left to match mathematical definition.
* Add type variables to the type specs to express the intent that all functions being composed together should have the same type signature (a single argument of type `X`, returning a value of type `X`).
* Add a test case that exposed the bug in the previous implementation that composed from left-to-right.

### CODE REVIEW

**Comment by paulhenrich** [comment]
Where is this called? I went looking for callers in case anyone was relying on the wrong behavior, but I couldn't find any.

**Comment by paulhenrich** [comment]
Not a caller, but while grepping I found another wrong implementation in https://github.com/basho/riak_repl/blob/develop/src/riak_repl_ring.erl#L498

**Comment by paulhenrich** [comment]
👍 Couldn't find any callers with a cursory search of GH and other OSS repos. We should probably still add something to the release notes (cc @angrycub)

**Comment by angrycub** [comment]
I agree.  We should note this in the release notes.  Could you write a comment containing the release note for this pull request.

**Comment by jvoegele** [comment]
@angrycub here is a comment for the release notes:

The `riak_core_util:compose/1` function has been modified to compose functions from right-to-left to match the mathematical definition of function composition.

**Pull request merged**
