### PR TITLE
Improve riak_ensemble integration

### PR DESCRIPTION
**Pull request by jtuple**
Update to correctly work with latest riak_ensemble.

Ensure that any failures during ensemble bootstrapping trigger future attempt to re-bootstrap the cluster.

This is the `riak_core` sibling pull-request for basho/riak_ensemble#10

### CODE REVIEW

**Comment by jonmeredith** [comment]
```
==> build (xref)
Query (XC - UC) || (XU - X - B - "(cluster_info|dtrace)" : Mod)
 answer [{{riak_core_claimant,bootstrap_members,1},
          {riak_ensemble_manager,cluster,0}},
         {{riak_core_claimant,maybe_bootstrap_root_ensemble,1},
          {riak_ensemble_manager,enabled,0}}]
 did not match []
```

**Comment by andrewjstone** [comment]
- [x] riak_tests
- [ ] dialyzer
- [x] xref
- [x] code review
- [x] make test

**Comment by andrewjstone** [comment]
Seeing the following dialyzer errors:

```
==> riak_core (dialyzer)
riak_core_claimant.erl:370: The pattern 'legacy' can never match the type {'error','invalid_resize_claim'} | {'ok',[{_,_},...]}
riak_core_claimant.erl:407: The pattern {'legacy', _} can never match the type {'error','invalid_resize_claim'} | {'ok',{'chstate_v2',_,'undefined' | [any()],{_,_},'undefined' | dict(),'undefined' | {_,_},'undefined' | [any()],[any()],_,'undefined' | [any()],'undefined' | [any()]}}
riak_core_claimant.erl:750: Call to missing or unexported function riak_ensemble_manager:enabled/0
riak_core_claimant.erl:768: Call to missing or unexported function riak_ensemble_manager:cluster/0
riak_core_claimant.erl:819: The pattern {'legacy', _} can never match the type {'error','invalid_resize_claim'} | {'ok',{'chstate_v2',_,'undefined' | [any()],{_,_},'undefined' | dict(),'undefined' | {_,_},'undefined' | [any()],[any()],_,'undefined' | [any()],'undefined' | [any()]}}
riak_core_claimant.erl:847: The pattern {'true', 'true'} can never match the type {'true','false'}
make: *** [dialyzer-run] Error 1
```

**Comment by seancribbs** [comment]
@andrewjstone This branch will need to be rebased, those errors should already be in the ignore file.

**Comment by andrewjstone** [comment]
@seancribbs I rebased against develop and got no change.

**Comment by seancribbs** [comment]
Sorry, ignore me, carry on.

**Comment by andrewjstone** [comment]
@seancribbs Line numbers are different in the ignore file. Also, the following 2 are new:

```
riak_core_claimant.erl:750: Call to missing or unexported function riak_ensemble_manager:enabled/0
riak_core_claimant.erl:768: Call to missing or unexported function riak_ensemble_manager:cluster/0
```

**Comment by andrewjstone** [comment]
@jtuple Once dialyzer and xref are fixed I'm +1 on this.

**Comment by jtuple** [comment]
+1 c8e56b6

**Comment by jtuple** [comment]
+1 ca958ed

**Comment by jtuple** [comment]
@borshop merge

**Pull request merged**
