### PR TITLE
Correct return type information on riak_core_bucket:set_bucket/2

### PR DESCRIPTION
**Pull request by seancribbs**
In basho/riak_api#62, the [dialyzer check fails](http://buildbot.bos1/builders/test-riak_api/builds/13/steps/shell_5/logs/stdio) because it believes the spec on riak_core_bucket:set_bucket/2, meaning that `{error, no_type}` would completely cover any returns matching `{error, _}`. However, validation errors may also be returned from `set_bucket/2`, as a list  of atom pairs that resulted from the call to riak_core_bucket_props:validate/4.

### CODE REVIEW

**Comment by reiddraper** [comment]
I'm not finding which code path will return the list of `[{atom(), atom()}]` from `set_bucket/2`. It looks like all of the `StoreFun`s return `ok`. What am I missing?

**Comment by seancribbs** [comment]
@reiddraper `riak_core_bucket_props:validate/4` is where that comes from.

**Comment by reiddraper** [comment]
Right, but we further process that return-value:

``` erlang
case riak_core_bucket_props:validate(update, Bucket, OldBucket, BucketProps0) of
    {ok, BucketProps} ->
        NewBucket = merge_props(BucketProps, OldBucket),
        StoreFun(Bucket, NewBucket);
    {error, Details} ->
        lager:error("Bucket properties validation failed ~p~n", [Details]),
        {error, Details}
end.
```

**Comment by seancribbs** [comment]
Correct, it's the second clause there I'm concerned with.

**Comment by reiddraper** [comment]
But the second clause returns `{error, Something}`, not `[{atom(), atom()}]`.

**Comment by reiddraper** [comment]
Derp, my misreading of this. +1

**Comment by seancribbs** [comment]
@borshop: retry

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
