### PR TITLE
Extend hashtree eqc test timeouts

### PR DESCRIPTION
**Pull request by kellymclaughlin**
The sha_test_ and eqc_test_ test suites in the hashtree module have
had trouble with slowness and timeouts on slower test machines.  Use
spawn so each test runs in its own process and extend the timeouts to
120 seconds to avoid these spurious failures.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
@borshop merge

**Comment by kellymclaughlin** [comment]
Local result for that test puts indicates it probably needs a higher timeout for slow machines:

```
riak_core_security_tests: security_test_ (user grant/revoke on type/bucket works)...[2.398 s] ok
```

**Comment by kellymclaughlin** [comment]
Extended the timeouts for the `riak_core_security_tests` tests to 60 seconds. There was a lot of whitespace shifting, but the only net change is really adding `{timeout, 60,` to each test case.

**Comment by kellymclaughlin** [comment]
@borshop: retry  fe640a3

**Comment by reiddraper** [comment]
I opened #590 about the particular failure we're seeing now. I vote for merging this in manually for now.

**Comment by kellymclaughlin** [comment]
Agreed, merging now

**Comment by reiddraper** [comment]
This just came back :(. [Here](http://buildbot.bos1/builders/test-riak_core/builds/1043/steps/shell_3/logs/stdio).

**Comment by reiddraper** [comment]
That build above is from #596.

**Pull request merged**
