### PR TITLE
Make riak_core_util:safe_rpc catch exit correctly

### PR DESCRIPTION
**Pull request by bowrocker**
The function was attempting to catch exit exception with 'EXIT':{noproc, ...}; should be exit:{noproc, ...}

http://erlang.org/doc/reference_manual/errors.html

Related riak_test PR:

https://github.com/basho/riak_test/pull/624

### CODE REVIEW

**Comment by reiddraper** [comment]
Thanks for catching this, I've assigned the 2.0-RC milestone to both of these issues.

**Comment by reiddraper** [comment]
cc @lordnull

**Comment by lordnull** [comment]
:+1: as the riak_test proves it's correctness.

Of course, bors isn't happy due to a spurious eunit failure (sha_test timeout).

**Comment by lordnull** [comment]
@borshop merge

**Comment by lordnull** [comment]
:+1:  b01f400

**Comment by lordnull** [comment]
@borshop merge

**Comment by reiddraper** [comment]
The failure we're seeing here is #590.

**Comment by cmeiklejohn** [comment]
Can we manually merge, @reiddraper?

**Comment by reiddraper** [comment]
Sure, and I appreciate that we talked about it in the comments. I just want there to at least be an explanation in the comments every time we decide to manually merge.

In this case, the explanation is that another test is blocking us, and we'd like to get a better handle on the outstanding issues, so having this closed will help us gain better visibility into what's remaining.

**Pull request merged**
