### PR TITLE
Fix hashtree:sha_test_ from timing out

### PR DESCRIPTION
**Pull request by reiddraper**
EQC takes a long time, and uses gigabytes of memory to generate 1MB
random binaries, as evidenced by:

```
eqc_gen:sample(eqc_gen:binary(1024 * 1024)).
```

We're still able to write a solid test, by ensuring that we always chunk
the binary into between 1 and 16 chunks. So instead of generating the
chunk size, we now generate the number of chunks, and derive chunk size
from that.

### CODE REVIEW

**Comment by reiddraper** [comment]
Fixes part of #585

**Comment by vinoski** [comment]
I'm +1 on this change. Originally on the slow build machines this test would take upwards of 90 seconds to execute, would use excessive memory, and would often core dump as a result. With this change the test reliably takes only 4 seconds.

**Comment by seancribbs** [comment]
Nitpick: there doesn't seem to be a reason for nested ?FOR_ALLs there. Won't shrinking be better if they are all in one generation step (perhaps using ?LET)?

**Comment by reiddraper** [comment]
> Nitpick: there doesn't seem to be a reason for nested ?FOR_ALLs there. Won't shrinking be better if they are all in one generation step (perhaps using ?LET)?

Indeed, you're exactly right. The nesting was required before, but in my change, I removed the need for nesting, without realizing it. I'll force-push a change up to here to amend that.

**Comment by reiddraper** [comment]
We'll still need one level of nesting, but that shouldn't be an issue.

**Comment by reiddraper** [comment]
I force-pushed 863baf0e8b4eb7d3c8ce9e77f62608411460020d.

**Comment by reiddraper** [comment]
Derp, I didn't `git add` before ammending, pushed another fix. 602e3aba69231ce636dbd04d6dd0f14ed61b069c.

**Comment by kellymclaughlin** [comment]
+1  602e3ab

**Comment by reiddraper** [comment]
Merging manually since develop is not passing buildbot tests yet.

**Pull request merged**
