### PR TITLE
Teach the sysmon handler about long schedules on ports

### PR DESCRIPTION
**Pull request by jonmeredith**
Found this in a customer log

```
2015-04-28 18:55:43.735 [info]
<0.233.0>@riak_core_sysmon_handler:handle_event:92 monitor long_schedule
[{erlang,process_info,[#Port<0.1461>,[registered_name,initial_call,current_function,message_queue_len]],[]},{riak_core_sysmon_handler,get_pretty_proc_info,2,[{file,[115,114,99,47,114,105,97,107,95,99,111,114,101,95,115,121,115,109,111,110,95,104,97,110,100,108,101,114,46,101,114,108]},{line,193}]},{riak_core_sysmon_handler,format_pretty_proc_info,2,[{file,[115,114,99,47,114,105,97,107,95,99,111,114,101,95,115,121,115,109,111,110,95,104,97,110,100,108,101,114,46,101,114,108]},{line,176}]},{riak_core_sysmon_handler,handle_event,2,[{file,[115,114,99,47,114,105,97,107,95,99,111,114,101,95,115,121,115,109,111,110,95,104,97,110,100,108,101,114,46,101,114,108]},{line,91}]},{gen_event,server_update,4,[{file,[103,101,110,95,101,118,101,110,116,46,101,114,108]},{line,522}]},{gen_event,server_notify,4,[{file,[103,101,110,95,101,118,101,110,116,46,101,114,108]},{line,504}]},{gen_event,handle_msg,5,[{file,[103,101,110,95,101,118,101,110,116,46,101,114,108]},{line,266}]},{proc_lib,wake_up,3,[{file,[112,114,111,99,95,108,105,98,46,101,114,108]},{line,249}]}]
```

Should now look something more like this (reporting timeout was turned
down to 1ms to provoke under a modest workload).

```
2015-04-30 08:58:58.471 [info]
<0.103.0>@riak_core_sysmon_handler:handle_event:92 monitor long_schedule
[{links,[<0.29108.41>]},{id,41723},{connected,<0.29108.41>}
,{input,3285848198},{output,45},{os_pid,undefined},{queue_size,0}]
[{timeout,2},{port_op,input}]
```

### CODE REVIEW

**Comment by russelldb** [comment]
Happy to review if you tell me how to test. How do I

> reporting timeout was turned
> down to 1ms to provoke under a modest workload

?

**Comment by jonmeredith** [comment]
Obviously you can trivially provoke this issue by applying this patch to erlang_js

```
diff --git a/c_src/spidermonkey_drv.c b/c_src/spidermonkey_drv.c
index aa17cef..aba3a16 100644
--- a/c_src/spidermonkey_drv.c
+++ b/c_src/spidermonkey_drv.c
@@ -16,6 +16,7 @@
 #include <string.h>
 #include <assert.h>
 #include <stdint.h>
+#include <unistd.h>
 #include <erl_driver.h>

 #include "spidermonkey.h"
@@ -51,6 +52,14 @@ static void stop(ErlDrvData handle);
 static void process(ErlDrvData handle, ErlIOVec *ev);
 static void ready_async(ErlDrvData handle, ErlDrvThreadData async_data);

+
+static void timeout(ErlDrvPort port)
+{
+  fprintf(stderr, "...timeout sleeping\r\n");
+  sleep(2);
+  fprintf(stderr, "...timeout slept - long_schedule\r\n");
+}
+
 static ErlDrvEntry spidermonkey_drv_entry = {
     init,                             /* init */
     start,                            /* startup */
@@ -62,7 +71,7 @@ static ErlDrvEntry spidermonkey_drv_entry = {
     NULL,                             /* finish */
     NULL,                             /* handle */
     NULL,                             /* control */
-    NULL,                             /* timeout */
+    timeout,                          /* timeout */
     process,                          /* process */
     ready_async,                      /* ready_async */
     NULL,                             /* flush */
@@ -217,6 +226,10 @@ static void stop(ErlDrvData handle) {
 static void process(ErlDrvData handle, ErlIOVec *ev) {
   spidermonkey_drv_t *dd = (spidermonkey_drv_t *) handle;

+  fprintf(stderr, "==== ERLANGJS DRIVER PROCESS - SETTING TIMER ===\r\n");
+
+  driver_set_timer(dd->port, 1); // make the sleep happen
+
   char *data = ev->binv[1]->orig_bytes;
   char *command = read_command(&data);
   if (strncmp(command, "ij", 2) == 0) {
```

adding this to your riak.conf

```
runtime_health.triggers.process.long_schedule = 1ms
```

firing up Riak on the console and you should see messages on startup, you can then provoke at will by running

```
 js_driver:new().
```

and you should see

```
18:16:17.162 [info] monitor long_schedule #Port<0.15141> name erlang_js_drv [{links,[<0.471.0>]},{id,55593},{connected,<0.471.0>},{input,0},{output,20401},{os_pid,undefined},{queue_size,0},{initial_call,{riak_kv_js_vm,init,1}}] [{timeout,2000},{port_op,timeout}]
```

in the logs. Simple really.

BTW, don't forget to compile with _EXACTLY_ R16B01, R16B02 or R17.

**Comment by cmeiklejohn** [comment]
:+1: f6fe5a2, reproduced and confirmed fix.

**Comment by cmeiklejohn** [comment]
bors appears broken; manually merging.

**Comment by DSomogyi** [comment]
create jira issue

**Pull request merged**
