### PR TITLE
Bugfix/set bucket 1.4

### LINKED ISSUE #366: Apply `set_bucket` fix to 1.4 and develop
Apply fix #365 to the 1.4 and develop branches.

### PR DESCRIPTION
**Pull request by jonmeredith**
Apply RZ's 1.3 change to make sure set_bucket uses the passed in ring for changes rather than the current ring.  Resolves #366.

### CODE REVIEW

**Comment by reiddraper** [comment]
+1

**Comment by rzezeski** [comment]
@reiddraper shouldn't this be a +1 on the commit since this is bor's enabled repo?

Looks like the build is failing due to trolling by meck.

**Comment by reiddraper** [comment]
@rzezeski indeed, whoops. Perhaps the merge-commit will pass. Though I would not be surprised if the 1.4 branch isn't passing at the moment.

**Comment by reiddraper** [comment]
I would suggest just manually merging this PR, since the build is already broken on 1.4.

**Comment by rzezeski** [comment]
I'm going to merge on Jon's behalf since he is busy with traveling and such.

**Pull request merged**
