### PR TITLE
Fixes #189 -- include socket peer info in lager messages

### LINKED ISSUE #189: Log handoff sender on node receiving handoff
Right now, we currently do not log which node sent the handoff on the receiving node:

```
2012-06-12 19:32:01.295 [info] <0.28019.343>@riak_core_handoff_receiver:handle_info:71 Handoff receiver for partition 35681192317648997026457149236237378409568665600 exited after processing 299 objects
```

It would be useful to know which node was sending the partition on the receiving node.

### PR DESCRIPTION
**Pull request by slfritchie**
Subject says it all ... the handoff protocol doesn't include the node name of the source node, so the best we can do without a protocol change (and capability negotiation and ...) is to log the socket's peername() info.

### CODE REVIEW

**Comment by engelsanchez** [comment]
Given all the talk about less erlangy log messages lately, I was wondering if it would be OK to display the peername as ip:port instead of directly printing the {IP, Port} tuple.  Or maybe [ip]:port to be more IPV6 friendly. Although I'm not sure how IPV6 addresses are represented here.

**Comment by seancribbs** [comment]
@engelsanchez Agree, `inet_parse:ntoa/1` works nicely for that purpose.

**Comment by engelsanchez** [comment]
Nice, that's perfect. Thanks @seancribbs

**Comment by engelsanchez** [comment]
Looks good. A bit of manual shows it working and showing the remote host and port on the receiving part. Caveat: I did not try it with SSL.

:+1: and merging now so it makes it into pre3

**Pull request merged**
