### PR TITLE
mod_set_forwarding crashes [JIRA: RIAK-1459]

### PR DESCRIPTION
**Pull request by andrewjstone**
handle modstate={deleted,_} in riak_kv_vnode:mod_set_forwarding/2

### CODE REVIEW

**Comment by andrewjstone** [comment]
Fixes this crash:

``` erlang
exception exit: {{{badrecord,state},[{riak_kv_vnode,set_vnode_forwarding,2,[{file,"src/riak_kv_vnode.erl"},{line,1028}]},{riak_core_vnode,mod_set_forwarding,2,[{file,"src/riak_core_vnode.erl"},{line,1050}]},{riak_core_vnode,handle_event,3,[{file,"src/riak_core_vnode.erl"},{line,713}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,505}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]},[{gen_fsm,terminate,7,[{file,"gen_fsm.erl"},{line,622}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
```

**Comment by russelldb** [comment]
That was my bad. Sorry @andrewjstone. Good catch +1.

**Comment by russelldb** [comment]
+1 80d9c1b23c8641709b1aa0c5f263d8c07044d02d

_edit sdc_: removed @borshop mention, not necessary

**Comment by seancribbs** [comment]
@borshop merge

**Comment by Basho-JIRA** [comment]
Adding to Jira to track bug found in testing 2.0.4 and with issue in GH. 

**_[posted via JIRA by Deb Rakow]**_

**Pull request merged**
