### PR TITLE
Bugfix/reip update claimant

### PR DESCRIPTION
**Pull request by jcapricebasho**
Two fixes to rename_node, fixing some issues discovered while renaming nodes with `riak-admin reip`.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Does this need to be on the RC milestone or the 2.0 final?

**Comment by jonmeredith** [comment]
Can be final - but it's a pretty quick review.

On Fri, Jun 13, 2014 at 9:41 AM, Kelly McLaughlin notifications@github.com
wrote:

> Does this need to be on the RC milestone or the 2.0 final?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/riak_core/pull/603#issuecomment-46026632.

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by reiddraper** [comment]
I'll grab review now. Assigning RC milestone

**Comment by reiddraper** [comment]
Put on the RC milestone.

**Comment by jonmeredith** [comment]
@reiddraper any objections or can we merge?

**Comment by jonmeredith** [comment]
Worth saying the rename_node is only called by reip so I'm not concerned about performance - but very interesting information to share.

**Comment by reiddraper** [comment]
@borshop merge

**Comment by reiddraper** [comment]
> Worth saying the rename_node is only called by reip so I'm not concerned about performance - but very interesting information to share.

Sounds good to me, I've asked borshop to merge.

**Pull request merged**
