### PR TITLE
Allow the vnode to change/provide the request to be forwarded

### PR DESCRIPTION
**Pull request by russelldb**
Required by the kv fix to basho/riak_kv#1046

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Looks like an `erlang_version` file snuck in with the commit.

**Comment by russelldb** [comment]
It was on purpose, for the buildbot, @engelsanchez made me do it.

**Comment by kellymclaughlin** [comment]
> It was on purpose, for the buildbot, @engelsanchez made me do it.

Gotcha, carry on then. :)

**Comment by kellymclaughlin** [comment]
Looks like the tests for the `riak_core_stat_cache` module introduce a reliance on a `riak_kv` module (https://github.com/basho/riak_core/blob/develop/src/riak_core_stat_cache.erl#L299) that will preclude the entire test suite from passing (probably one problem among many)

```
module 'riak_core_stat_cache'
  *** context setup failed ***
::{{undefined_module,riak_kv_stat},
 [{meck_proc,resolve_can_expect,3,[{file,"src/meck_proc.erl"},{line,402}]},
  {meck_proc,init,1,[{file,"src/meck_proc.erl"},{line,194}]},
  {gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},
  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
```

**Comment by russelldb** [comment]
I wonder what is up here. Meck used to be OK with this. It isn't a real dep, it's just an atom for meck to create a fake module around (I had this conversation when I originally committed the test and it worked then.) I wonder if meck has changed to require the modules you mock out to actually exist? (Hence why I blame meck!)

**Comment by russelldb** [comment]
Found it, meck now requires `non_strict` for mocking modules that don't exist on the path. https://github.com/eproxus/meck

**Comment by russelldb** [comment]
Will fix.

**Comment by kellymclaughlin** [comment]
The [`pool_death_test`](https://github.com/basho/riak_core/blob/develop/src/riak_core_vnode.erl#L1065) in `riak_core_vnode` also seems to be suffering from this.

```
riak_core_vnode: pool_death_test (module 'riak_core_vnode')...*failed*
::{{undefined_module,test_vnode},
 [{meck_proc,resolve_can_expect,3,[{file,"src/meck_proc.erl"},{line,402}]},
  {meck_proc,init,1,[{file,"src/meck_proc.erl"},{line,194}]},
  {gen_server,init_it,6,[{file,"gen_server.erl"},{line,304}]},
  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]}
```

I'll spend a bit of time to look into the meck version theory more.

**Comment by kellymclaughlin** [comment]
> Found it, meck now requires non_strict for mocking modules that don't exist on the path. https://github.com/eproxus/meck

Ahh, you beat me to it. Cool.

**Comment by kellymclaughlin** [comment]
After a liberal helping of `non_strict`:

```
=======================================================
  All 323 tests passed.
Cover analysis: /home/kelly/basho/repos/riak_core/.eunit/index.html
```

**Comment by russelldb** [comment]
Nicely done!!

**Comment by slfritchie** [comment]
+1 4a38a91

**Comment by slfritchie** [comment]
@borshop merge

**Comment by slfritchie** [comment]
@borshop: retry

**Comment by slfritchie** [comment]
@borshop: retry

**Comment by slfritchie** [comment]
@borshop: retry

while [ 1 ]; do echo @borshop: retry | github-shout; done

**Comment by cmeiklejohn** [comment]
Haha.

**Comment by slfritchie** [comment]
+1 6525a03

**Comment by slfritchie** [comment]
+1 6525a03147c97baa7ed939f4670891411d1d2279

**Comment by slfritchie** [comment]
@borshop merge

**Comment by jadeallenx** [comment]
Wishing I could favorite the crap out of https://github.com/basho/riak_core/pull/651#issuecomment-63600612

**Pull request merged**
