### PR TITLE
Add clique_status:usage() return for case when we get neither Index or ID

### PR DESCRIPTION
**Pull request by JeetKunDoug**
Requires https://github.com/basho/clique/pull/25. Addresses https://github.com/basho/riak_core/pull/659#issuecomment-66381007

### CODE REVIEW

**Comment by jadeallenx** [comment]
:+1:

**Comment by andrewjstone** [comment]
rebar.config actually needs to change also so that it includes a later version of clique

**Comment by andrewjstone** [comment]
@JeetKunDoug I hope you don't mind, but I made the change to rebar.config and pushed it. It all works so +1.

**Comment by andrewjstone** [comment]
:+1:  8424513

**Comment by JeetKunDoug** [comment]
@andrewjstone thanks for wrapping this up - I will never mind someone finishing up my work for me :)

**Pull request merged**
