### PR TITLE
Improve handoff enable/disable config naming

### PR DESCRIPTION
**Pull request by nickelization**
This avoids the confusing double-negative situation where you have to turn off the disabling of handoff in order to enable it. Now you just say e.g. "set handoff.inbound=on" to enable inbound handoff, and "set handoff.inbound=off" to disable it.

### CODE REVIEW

**Comment by macintux** [comment]
Reviewing

**Comment by andrewjstone** [comment]
@borshop retry

**Comment by andrewjstone** [comment]
:+1: 2e2feee

**Comment by andrewjstone** [comment]
Rebased to deal with the whitelisting merge.

**Pull request merged**
