### PR TITLE
Make riak_core_vnode_sup start options configurable

### PR DESCRIPTION
**Pull request by jbrisbin**
The default start options for the vnode supervisor don't fit every situation. I've added code to make it configurable by adding something like:

{riak_core_vnode_sup, [
  {lifecycle_options, {
    {simple_one_for_one, 10, 10}, 
    [
      {undefined, {riak_core_vnode, start_link, []}, temporary, brutal_kill, worker, dynamic}
    ]
  }]
}

Which allows you to make vnodes fit the situation of your particular application (e.g. without brutal_kill etc...).

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thanks, Jon. 

This one is added to the review queue. We'll merge/get back to you with comments ASAP. 

Keep the code coming. 

Mark

**Comment by rzezeski** [comment]
Hey, Jon.

Have you used this to change anything other then the shutdown method?

**Comment by jbrisbin** [comment]
I haven't personally, no.

**Comment by rzezeski** [comment]
So what I'm wondering is if we really want a config for the entire child spec.  It seems just a config for the shutdown method is enough.  This could just be some undocumented thing that devs can make use of.  But I also wonder why the shutdown method is `brutal_kill` to begin with.  I wonder if this is something you'd want to be able to change per vnode type, but I don't think there is anyway to achieve that.

Anyways, I'm rambling.  Could you humor me and give me the use case where you needed this to be a timeout?

**Comment by russelldb** [comment]
Hey Jon,

It's been a while. Do you still need this feature? I agree with Ryan that being able to configure the entire child spec like this is overkill. Given how much riak_core has moved on, and how small the change is, would you mind re-submitting if you still value the change?

**Pull request closed without merging**
